name: Push

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install -n --no-ansi
      - name: Run checks
        run: |
          source .venv/bin/activate
          black --check .
          isort . --profile black --check
          mypy .
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest .
